# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUnifiMcp < Formula
  desc "MCP server for UniFi Network Controller"
  homepage "https://github.com/claytono/go-unifi-mcp"
  version "0.1.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.1.1/go-unifi-mcp_darwin_amd64.tar.gz"
      sha256 "621a2234b23db6b9cb70724c515b31e6996847262158777d42f4644c6124e77e"

      def install
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.1.1/go-unifi-mcp_darwin_arm64.tar.gz"
      sha256 "f26e9bd14c6777c2b734a10bab5087c4df6810e78449aa6899e63c4b5b1fd79b"

      def install
        bin.install "go-unifi-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.1.1/go-unifi-mcp_linux_amd64.tar.gz"
      sha256 "e14abb0ac8eebc178591037a5806197ec269a31700c88a1ec9e90bf61ccb54e8"
      def install
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.1.1/go-unifi-mcp_linux_arm64.tar.gz"
      sha256 "30326d40423376592f1f2c39a31177ce17d110db1bd053033f61be451115c9e6"
      def install
        bin.install "go-unifi-mcp"
      end
    end
  end

  test do
    system "#{bin}/go-unifi-mcp", "--help"
  end
end
