# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUnifiMcp < Formula
  desc "MCP server for UniFi Network Controller"
  homepage "https://github.com/claytono/go-unifi-mcp"
  version "0.3.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.3.0/go-unifi-mcp_darwin_amd64.tar.gz"
      sha256 "592e03ee56042c6151a88c533ad92ae6b5d60ce798586054faeee9de2f7d8e4b"

      define_method(:install) do
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.3.0/go-unifi-mcp_darwin_arm64.tar.gz"
      sha256 "38f8a9cadd08dad39997c8e8f60196d17a8e83dbafa480f913b6fab9bf405100"

      define_method(:install) do
        bin.install "go-unifi-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.3.0/go-unifi-mcp_linux_amd64.tar.gz"
      sha256 "62e33a3d534aa5d1b735cc3dc03bf4da2686157258cbb0818153ecf8153a64ac"
      define_method(:install) do
        bin.install "go-unifi-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/claytono/go-unifi-mcp/releases/download/v0.3.0/go-unifi-mcp_linux_arm64.tar.gz"
      sha256 "7af17a0d0dd26e3e749af307784c778583eeb7518c7fd2c9f1adc9a14811bcd0"
      define_method(:install) do
        bin.install "go-unifi-mcp"
      end
    end
  end

  test do
    system "#{bin}/go-unifi-mcp", "--help"
  end
end
